name: Full CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Tests
        working-directory: ./backend
        run: npm test

      - name: Sonar Scan
        #if: false
        uses: sonarsource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        #if: false
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Image
        #if: false
        run: |
          docker build -t silencfox/simpleapi:latest ./backend
          docker push silencfox/simpleapi:latest
          #docker push silencfox/simpleapi:${{ github.sha }}

  deploy:
    needs: docker
    name: deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    #defaults:
    #  run:
    #    working-directory: infra
    strategy:
      matrix:
        environment: [DEV, QA, PROD]

    environment: ${{ matrix.environment }}

    steps:

      - uses: actions/checkout@v4

      - name: Despliegue
        run: echo "tarea de despliegue Running for ${{ matrix.environment }}"

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: ReplaceTokens
        uses: qetza/replacetokens-action@v1
        with:
          sources: |
            **/*.json;!**/*.dev.json;!**/vars.json => _tmp/*.json
            **/*.yml;**/*.yaml;**/*.tfvars;**/backend.tf
          variables: '[${{ toJSON(vars) }},${{ toJSON(secrets) }},"$ENV"]'

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform validate
        working-directory: ./infra
        run: terraform validate

      - name: Terraform Plan
        if: false
        working-directory: ./infra
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform apply
        if: github.ref == 'refs/heads/main'
        working-directory: ./infra
        run: terraform apply --auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}


      - name: Export Terraform Outputs to JSON
        working-directory: ./infra
        id: tf_outputs
        run: |
          terraform output -json > infra_outputs.json
          echo "Outputs generados:"
          cat infra_outputs.json

      #- name: Upload Terraform Output Artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: infra_outputs
      #    path: ./infra/infra_outputs.json

      - name: Test vars
        working-directory: ./infra
        run: |
          MYVAR="Hola Mundo DK"
          echo $MYVAR
          
      - name: Export outputs as GitHub Env Vars
        working-directory: ./infra
        run: |
          ALB_URL=$(terraform output -raw alb_dns_name | sed 's/::debug::.*//' | tr -d '\r')
          S3_BUCKET=$(terraform output -raw s3_bucket | sed 's/::debug::.*//' | tr -d '\r')
          RDS_ENDPOINT=$(terraform output -raw rds_endpoint | sed 's/::debug::.*//' | tr -d '\r')
          RDS_ENDPOINT_MYSQL=$(terraform output -raw rds_endpoint_mysql | sed 's/::debug::.*//' | tr -d '\r')
          S3_WEBSITE_URL=$(terraform output -raw s3_website_url | sed 's/::debug::.*//' | tr -d '\r')
          #echo "ALB_DNS_NAME2=$(echo $ALB_URL)" >> $GITHUB_ENV
          #echo "ALB_DNS_NAME2=$ALB_URL" >> $GITHUB_ENV
          
          echo 'ALB_DNS_NAME<<EOF' >> $GITHUB_ENV
          echo "$ALB_URL" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

          echo 'S3_BUCKET<<EOF' >> $GITHUB_ENV
          echo "$S3_BUCKET" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

          echo 'RDS_ENDPOINT<<EOF' >> $GITHUB_ENV
          echo "$RDS_ENDPOINT" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

          echo 'RDS_ENDPOINT_MYSQL<<EOF' >> $GITHUB_ENV
          echo "$RDS_ENDPOINT_MYSQL" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

          echo 'S3_WEBSITE_URL<<EOF' >> $GITHUB_ENV
          echo "$S3_WEBSITE_URL" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

          
          #echo "S3_BUCKET=$(terraform output -raw s3_bucket)" >> $GITHUB_ENV
          #echo "RDS_ENDPOINT=$(terraform output -raw rds_endpoint)" >> $GITHUB_ENV
          #echo "RDS_ENDPOINT_MYSQL=$(terraform output -raw rds_endpoint_mysql)" >> $GITHUB_ENV
          #echo "S3_BUCKET=$(terraform output -raw s3_bucket)" >> $GITHUB_ENV
          #echo "S3_WEBSITE_URL=$(terraform output -raw s3_website_url)" >> $GITHUB_ENV


      - name: Mostrar outputs exportados
        env:
          ALB: ${{ env.ALB_DNS_NAME }}
          ALB2: ${{ env.ALB_DNS_NAME2 }}
        run: |
          echo "Usando ALB: $ALB"
          echo "ALB_DNS_NAME: $ALB_DNS_NAME"
          echo "S3_BUCKET: $S3_BUCKET"
          echo "RDS_ENDPOINT: $RDS_ENDPOINT"
          echo "RDS_ENDPOINT_MYSQL: $RDS_ENDPOINT_MYSQL"
          echo "S3_WEBSITE_URL: $S3_WEBSITE_URL"

      - name: ReplaceTokens
        uses: qetza/replacetokens-action@v1
        with:
          sources: |
            **/*.json;!**/*.dev.json;!**/vars.json => _tmp/*.json
            **/*.yml;**/*.yaml;**/*.tfvars;**/backend.tf
            **/app.js;**/db.js
          variables: '[${{ toJSON(vars) }},${{ toJSON(secrets) }},"$ENV"]'
          
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        #run: aws s3 sync ./frontend s3://devsu-app-test-bucket
        run: aws s3 sync ./frontend s3://$S3_BUCKET
        #--delete
    
      - name: Terraform destroy
        if: false
        working-directory: ./infra
        run: terraform destroy --auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}



      #- name: Deploy to K8s via kubectl
      #  uses: azure/k8s-deploy@v4
      #  with:
      #    manifests: |
      #      k8s/deployment.yaml
      #    images: |
      #      mydocker/myapp:${{ github.sha }}
      #    namespace: production
      #  env:
      #    KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}





  destroy:
    needs: deploy
    name: destroy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    #defaults:
    #  run:
    #    working-directory: infra
    strategy:
      matrix:
        environment: [DEV, QA, PROD]

    environment: ${{ matrix.environment }}

    steps:

      - uses: actions/checkout@v4

      - name: Despliegue
        run: echo "tarea de despliegue Running for ${{ matrix.environment }}"

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: ReplaceTokens
        uses: qetza/replacetokens-action@v1
        with:
          sources: |
            **/*.json;!**/*.dev.json;!**/vars.json => _tmp/*.json
            **/*.yml;**/*.yaml;**/*.tfvars;**/backend.tf
          variables: '[${{ toJSON(vars) }},${{ toJSON(secrets) }},"$ENV"]'

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform validate
        working-directory: ./infra
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./infra
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    
      - name: Terraform destroy
        working-directory: ./infra
        run: terraform destroy --auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    

      #- name: Terraform Apply
      #  if: github.ref == 'refs/heads/main'
      #  run: terraform apply -auto-approve

        
      #- name: Deploy to K8s via kubectl
      #  uses: azure/k8s-deploy@v4
      #  with:
      #    manifests: |
      #      k8s/deployment.yaml
      #    images: |
      #      mydocker/myapp:${{ github.sha }}
      #    namespace: production
      #  env:
      #    KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}


