name: Full CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Tests
        working-directory: ./backend
        run: npm test

      - name: Sonar Scan
        if: false
        uses: sonarsource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        if: false
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Image
        if: false
        run: |
          docker build -t silencfox/simpleapi:latest ./backend
          docker push silencfox/simpleapi:latest
          #docker push silencfox/simpleapi:${{ github.sha }}

  deploy:
    needs: docker
    name: deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    defaults:
      run:
        working-directory: infra
    strategy:
      matrix:
        environment: [DEV, QA, PROD]

    environment: ${{ matrix.environment }}

    steps:

      - uses: actions/checkout@v4

      - name: Despliegue
        run: echo "tarea de despliegue Running for ${{ matrix.environment }}"

      - name: Define variables for replace tokens
        run: |
          echo "{\"ENVIRONMENT\":\"${{ matrix.environment }}\"}" > env.json
          
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: ReplaceTokens
        uses: qetza/replacetokens-action@v1
        with:
          sources: |
            **/*.json;!**/*.dev.json;!**/vars.json => _tmp/*.json
            **/*.yml;**/*.yaml;**/*.tfvars;**/backend.tf
          variables: '[${{ toJSON(vars) }},${{ toJSON(secrets) }},"$ENV_VARS",${{ file("env.json") }}]'

      - name: Terraform Init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    
      #- name: Terraform Apply
      #  if: github.ref == 'refs/heads/main'
      #  run: terraform apply -auto-approve

        
      #- name: Deploy to K8s via kubectl
      #  uses: azure/k8s-deploy@v4
      #  with:
      #    manifests: |
      #      k8s/deployment.yaml
      #    images: |
      #      mydocker/myapp:${{ github.sha }}
      #    namespace: production
      #  env:
      #    KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}


